# Survival analysis configuration

# Path to data (will be overridden by BIOBANK_DATA_PATH environment variable)
data_path: "data/"

# Outcome columns
event_column: "MACE"  # Binary indicator (1=event occurred, 0=censored)
time_column: "MACE_days"  # Time to event or censoring in days

# Directory to save results
results_directory: "results/survival_analysis"

# Models to run
models:
  - "cox_ph"  # Cox Proportional Hazards
  # - "rsf"     # Random Survival Forest
  # - "xgbse"   # XGBoost Survival Embeddings

# Parameters for Cox PH model
cox_params:
  penalizer: 0.1
  l1_ratio: 0.5

# Parameters for Random Survival Forest
rsf_params:
  n_estimators: 100
  max_depth: 5
  min_samples_split: 10
  min_samples_leaf: 5
  max_features: "sqrt"
  n_jobs: -1
  random_state: 42

# Parameters for XGBSE
xgbse_params:
  learning_rate: 0.1
  n_estimators: 100
  max_depth: 4
  subsample: 0.8
  colsample_bytree: 0.8

# Time horizons for evaluation (in days)
time_horizons:
  - 365    # 1 year
  - 1095   # 3 years
  - 1825   # 5 years
