# Advanced Survival Analysis Configuration
outcome: "MACE"  # Binary outcome column (1=event occurred, 0=censored)
outcome_time: "MACE_days"  # Time to event column (in days)
results_directory: "results/advanced_survival_analysis"
experiment_name: "advanced_survival"

# AFT Model Parameters
aft_model_type: "weibull"  # Options: "weibull" or "lognormal"
aft_penalizer: 0.1  # Regularization strength

# Random Survival Forest Parameters
rsf_n_estimators: 100  # Number of trees
rsf_max_depth: 8  # Maximum depth of trees (null = unlimited)
rsf_min_samples_split: 10  # Minimum samples required to split a node
rsf_min_samples_leaf: 5  # Minimum samples required at a leaf node

# DeepSurv Parameters
deepsurv_hidden_layers: [64, 32]  # List of hidden layer sizes
deepsurv_learning_rate: 0.001  # Learning rate for optimizer
deepsurv_batch_size: 64  # Batch size for training
deepsurv_epochs: 100  # Maximum number of training epochs
deepsurv_patience: 10  # Patience for early stopping
deepsurv_device: "cpu"  # Device to use (cpu or cuda)
