# Advanced Survival Analysis Configuration
outcome: "MACE"  # Binary outcome column (1=event occurred, 0=censored)
outcome_time: "MACE_days"  # Time to event column (in days)
results_directory: "results/advanced_survival_analysis"
experiment_name: "advanced_survival"


# Random Survival Forest Parameters
rsf_n_estimators: 5  # Number of trees
rsf_max_depth: 5  # Maximum depth of trees (null = unlimited)
rsf_min_samples_split: 3  # Minimum samples required to split a node
rsf_min_samples_leaf: 5 # Minimum samples required at a leaf node
